spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.url:localhost}:${db.port:3306:null}/${db.scheme:null}?serverTimezone=Asia/Seoul
    username: ${db.user:null}
    password: ${db.pass:null}
    hikari:
      maximum-pool-size: 20
      pool-name: SpringBootHikariCP
      minimum-idle: 5
      idle-timeout: 30000
  devtools:
    livereload:
      enabled: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.zaxxer.hikari.HikariConfig: INFO #DEBUG
    com.zaxxer.hikari: INFO #TRACE
