ALTER TABLE BOARD DROP CONSTRAINT FK_USER_ID;
DROP TABLE IF EXISTS TEST_USER;
DROP TABLE IF EXISTS BOARD;

CREATE TABLE TEST_USER(
    id VARBINARY NOT NULL,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE BOARD(
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(6000) NOT NULL,
    user_id VARBINARY NOT NULL,
    PRIMARY KEY (id),
    constraint FK_USER_ID
        FOREIGN KEY (user_id) REFERENCES TEST_USER(id)
                  on DELETE CASCADE
);


